// File: /Users/liborballaty/LocalProjects/GitHubProjectsDocuments/llm-test-suite/performance-prompts.js
// Description: Performance test prompts aligned with PROMPT-SCHEMA v2.2.0 - 50 prompts across 5 input token ranges
// Author: Libor Ballaty <libor@arionetworks.com>
// Created: 2026-03-23
// Last Updated: 2026-03-26

// Performance test prompts - 50 prompts across 5 input token ranges
// All prompts now follow PROMPT-SCHEMA v2.2.0 with required fields: id, category, vendor, question, expectedTopics, complexity

export const PERFORMANCE_PROMPTS = {
  RUN_1_TINY: [
    { id: 'PERF_GDPR_FACTUAL_TINY_01', category: 'performance_test', vendor: 'Generic', question: 'What is GDPR?', expectedTopics: ['regulation', 'privacy', 'EU'], complexity: 'beginner', standard: 'GDPR', knowledgeType: 'FACTUAL', estimatedTokens: 4 },
    { id: 'PERF_ISO27001_FACTUAL_TINY_02', category: 'performance_test', vendor: 'Generic', question: 'What is ISO 27001?', expectedTopics: ['security', 'management', 'standard'], complexity: 'beginner', standard: 'ISO_27001', knowledgeType: 'FACTUAL', estimatedTokens: 5 },
    { id: 'PERF_SOC2_FACTUAL_TINY_03', category: 'performance_test', vendor: 'Generic', question: 'What is SOC 2?', expectedTopics: ['audit', 'service organization', 'trust'], complexity: 'beginner', standard: 'SOC_2', knowledgeType: 'FACTUAL', estimatedTokens: 4 },
    { id: 'PERF_HIPAA_FACTUAL_TINY_04', category: 'performance_test', vendor: 'Generic', question: 'What is HIPAA?', expectedTopics: ['healthcare', 'privacy', 'security'], complexity: 'beginner', standard: 'HIPAA', knowledgeType: 'FACTUAL', estimatedTokens: 4 },
    { id: 'PERF_PCIDSS_FACTUAL_TINY_05', category: 'performance_test', vendor: 'Generic', question: 'What is PCI-DSS?', expectedTopics: ['payment', 'card', 'security'], complexity: 'beginner', standard: 'PCI_DSS', knowledgeType: 'FACTUAL', estimatedTokens: 4 },
    { id: 'PERF_EUAI_FACTUAL_TINY_06', category: 'performance_test', vendor: 'Generic', question: 'What is the EU AI Act?', expectedTopics: ['AI', 'regulation', 'EU'], complexity: 'beginner', standard: 'EU_AI_ACT', knowledgeType: 'FACTUAL', estimatedTokens: 6 },
    { id: 'PERF_FEDRAMP_FACTUAL_TINY_07', category: 'performance_test', vendor: 'Generic', question: 'What is FedRAMP?', expectedTopics: ['federal', 'cloud', 'authorization'], complexity: 'beginner', standard: 'FedRAMP', knowledgeType: 'FACTUAL', estimatedTokens: 4 },
    { id: 'PERF_NISTCSF_FACTUAL_TINY_08', category: 'performance_test', vendor: 'Generic', question: 'What is NIST CSF?', expectedTopics: ['cybersecurity', 'framework', 'NIST'], complexity: 'beginner', standard: 'NIST_CSF', knowledgeType: 'FACTUAL', estimatedTokens: 5 },
    { id: 'PERF_ISO27701_FACTUAL_TINY_09', category: 'performance_test', vendor: 'Generic', question: 'What is ISO 27701?', expectedTopics: ['privacy', 'management', 'PIMS'], complexity: 'beginner', standard: 'ISO_27701', knowledgeType: 'FACTUAL', estimatedTokens: 5 },
    { id: 'PERF_CMMC_FACTUAL_TINY_10', category: 'performance_test', vendor: 'Generic', question: 'What is CMMC?', expectedTopics: ['cybersecurity', 'maturity', 'defense'], complexity: 'beginner', standard: 'CMMC_2_0', knowledgeType: 'FACTUAL', estimatedTokens: 4 }
  ],

  RUN_2_SHORT: [
    { id: 'PERF_GDPR_FACTUAL_SHORT_01', category: 'performance_test', vendor: 'Generic', question: 'What are the main principles of GDPR?', expectedTopics: ['principles', 'lawfulness', 'transparency', 'purpose limitation'], complexity: 'beginner', standard: 'GDPR', knowledgeType: 'FACTUAL', estimatedTokens: 8 },
    { id: 'PERF_ISO27001_FACTUAL_SHORT_02', category: 'performance_test', vendor: 'Generic', question: 'What are the key requirements of ISO 27001 certification?', expectedTopics: ['ISMS', 'controls', 'audit', 'certification'], complexity: 'beginner', standard: 'ISO_27001', knowledgeType: 'FACTUAL', estimatedTokens: 11 },
    { id: 'PERF_SOC2_FACTUAL_SHORT_03', category: 'performance_test', vendor: 'Generic', question: 'What are the Trust Services Criteria in SOC 2?', expectedTopics: ['security', 'availability', 'confidentiality', 'privacy'], complexity: 'beginner', standard: 'SOC_2', knowledgeType: 'FACTUAL', estimatedTokens: 10 },
    { id: 'PERF_HIPAA_FACTUAL_SHORT_04', category: 'performance_test', vendor: 'Generic', question: 'What are the main HIPAA privacy rule requirements?', expectedTopics: ['PHI', 'privacy', 'patient rights', 'notice'], complexity: 'beginner', standard: 'HIPAA', knowledgeType: 'FACTUAL', estimatedTokens: 10 },
    { id: 'PERF_PCIDSS_FACTUAL_SHORT_05', category: 'performance_test', vendor: 'Generic', question: 'What are the 12 requirements of PCI-DSS?', expectedTopics: ['cardholder data', 'firewall', 'encryption', 'access control'], complexity: 'beginner', standard: 'PCI_DSS', knowledgeType: 'FACTUAL', estimatedTokens: 10 },
    { id: 'PERF_EUAI_FACTUAL_SHORT_06', category: 'performance_test', vendor: 'Generic', question: 'What are the risk levels in the EU AI Act?', expectedTopics: ['high-risk', 'unacceptable', 'limited risk', 'minimal risk'], complexity: 'beginner', standard: 'EU_AI_ACT', knowledgeType: 'FACTUAL', estimatedTokens: 11 },
    { id: 'PERF_FEDRAMP_FACTUAL_SHORT_07', category: 'performance_test', vendor: 'Generic', question: 'What are the FedRAMP impact levels?', expectedTopics: ['low', 'moderate', 'high', 'impact'], complexity: 'beginner', standard: 'FedRAMP', knowledgeType: 'FACTUAL', estimatedTokens: 7 },
    { id: 'PERF_NISTCSF_FACTUAL_SHORT_08', category: 'performance_test', vendor: 'Generic', question: 'What are the 6 functions of NIST CSF?', expectedTopics: ['identify', 'protect', 'detect', 'respond', 'recover', 'govern'], complexity: 'beginner', standard: 'NIST_CSF', knowledgeType: 'FACTUAL', estimatedTokens: 10 },
    { id: 'PERF_ISO27701_RELATIONAL_SHORT_09', category: 'performance_test', vendor: 'Generic', question: 'How does ISO 27701 extend ISO 27001?', expectedTopics: ['privacy', 'PIMS', 'extension', 'PII'], complexity: 'intermediate', standard: 'ISO_27701', knowledgeType: 'RELATIONAL', estimatedTokens: 9 },
    { id: 'PERF_CMMC_FACTUAL_SHORT_10', category: 'performance_test', vendor: 'Generic', question: 'What are the CMMC 2.0 certification levels?', expectedTopics: ['level 1', 'level 2', 'level 3', 'maturity'], complexity: 'beginner', standard: 'CMMC_2_0', knowledgeType: 'FACTUAL', estimatedTokens: 9 }
  ],

  RUN_3_MEDIUM: [
    { id: 'PERF_HIPAA_PROCEDURAL_MEDIUM_01', category: 'performance_test', vendor: 'Generic', question: 'For a small healthcare organization processing patient data, what are the key HIPAA Security Rule requirements for protecting electronic protected health information?', expectedTopics: ['encryption', 'access control', 'audit trails', 'ePHI'], complexity: 'intermediate', standard: 'HIPAA', knowledgeType: 'PROCEDURAL', estimatedTokens: 25 },
    { id: 'PERF_GDPR_PROCEDURAL_MEDIUM_02', category: 'performance_test', vendor: 'Generic', question: 'What are the specific documentation requirements needed to demonstrate GDPR accountability, including records of processing activities and data protection impact assessments?', expectedTopics: ['RoPA', 'DPIA', 'accountability', 'documentation'], complexity: 'intermediate', standard: 'GDPR', knowledgeType: 'PROCEDURAL', estimatedTokens: 24 },
    { id: 'PERF_ISO27001_RELATIONAL_MEDIUM_03', category: 'performance_test', vendor: 'Generic', question: 'How do ISO 27001 Annex A controls relate to SOC 2 Trust Services Criteria, and what are the main overlaps?', expectedTopics: ['control mapping', 'overlap', 'security controls'], complexity: 'intermediate', standard: 'ISO_27001', knowledgeType: 'RELATIONAL', estimatedTokens: 23 },
    { id: 'PERF_PCIDSS_PROCEDURAL_MEDIUM_04', category: 'performance_test', vendor: 'Generic', question: 'What are the steps a financial services company must take to achieve PCI-DSS compliance for payment card processing?', expectedTopics: ['assessment', 'implementation', 'validation', 'compliance'], complexity: 'intermediate', standard: 'PCI_DSS', knowledgeType: 'PROCEDURAL', estimatedTokens: 21 },
    { id: 'PERF_EUAI_PROCEDURAL_MEDIUM_05', category: 'performance_test', vendor: 'Generic', question: 'For an AI system used in hiring decisions, what makes it high-risk under the EU AI Act and what requirements apply?', expectedTopics: ['high-risk', 'transparency', 'human oversight', 'conformity assessment'], complexity: 'intermediate', standard: 'EU_AI_ACT', knowledgeType: 'PROCEDURAL', estimatedTokens: 25 },
    { id: 'PERF_FEDRAMP_RELATIONAL_MEDIUM_06', category: 'performance_test', vendor: 'Generic', question: 'What are the key differences between FedRAMP Moderate and High authorization levels for cloud service providers?', expectedTopics: ['impact level', 'controls', 'NIST 800-53', 'differences'], complexity: 'intermediate', standard: 'FedRAMP', knowledgeType: 'RELATIONAL', estimatedTokens: 19 },
    { id: 'PERF_NISTCSF_PROCEDURAL_MEDIUM_07', category: 'performance_test', vendor: 'Generic', question: 'How does implementing NIST Cybersecurity Framework help organizations manage cyber risk and what are the implementation tiers?', expectedTopics: ['risk management', 'tiers', 'framework', 'implementation'], complexity: 'intermediate', standard: 'NIST_CSF', knowledgeType: 'PROCEDURAL', estimatedTokens: 21 },
    { id: 'PERF_ISO27701_PROCEDURAL_MEDIUM_08', category: 'performance_test', vendor: 'Generic', question: 'What privacy controls does ISO 27701 add beyond ISO 27001 for organizations acting as PII processors?', expectedTopics: ['PII processor', 'privacy controls', 'additional controls'], complexity: 'intermediate', standard: 'ISO_27701', knowledgeType: 'PROCEDURAL', estimatedTokens: 19 },
    { id: 'PERF_CMMC_PROCEDURAL_MEDIUM_09', category: 'performance_test', vendor: 'Generic', question: 'What are the assessment requirements for achieving CMMC Level 2 certification for defense contractors?', expectedTopics: ['assessment', 'certification', 'NIST 800-171', 'C3PAO'], complexity: 'intermediate', standard: 'CMMC_2_0', knowledgeType: 'PROCEDURAL', estimatedTokens: 17 },
    { id: 'PERF_ISO27035_RELATIONAL_MEDIUM_10', category: 'performance_test', vendor: 'Generic', question: 'How does ISO 27035 incident management integrate with GDPR data breach notification requirements including the 72-hour rule?', expectedTopics: ['incident management', 'breach notification', '72 hours', 'integration'], complexity: 'advanced', standard: 'ISO_27035', knowledgeType: 'RELATIONAL', estimatedTokens: 21 }
  ],

  RUN_4_LONG: [
    { id: 'PERF_SOC2_PROCEDURAL_LONG_01', category: 'performance_test', vendor: 'Generic', question: 'For a SaaS company with 100 employees operating globally, what is the complete workflow needed to achieve SOC 2 Type II certification, including scoping decisions, control implementation, evidence collection, and audit preparation, with estimated timeframes for each phase?', expectedTopics: ['scoping', 'control implementation', 'evidence collection', 'Type II', 'workflow'], complexity: 'advanced', standard: 'SOC_2', knowledgeType: 'PROCEDURAL', estimatedTokens: 44 },
    { id: 'PERF_GDPR_SYNTHESIS_LONG_02', category: 'performance_test', vendor: 'Generic', question: 'A multinational corporation processes personal data of EU citizens, California residents, and Canadian customers. What are the overlapping requirements between GDPR, CCPA/CPRA, and PIPEDA that can be addressed with unified privacy controls, and what are the unique requirements for each regulation?', expectedTopics: ['GDPR', 'CCPA', 'PIPEDA', 'overlap', 'unified controls'], complexity: 'advanced', standard: 'GDPR', knowledgeType: 'SYNTHESIS', estimatedTokens: 48 },
    { id: 'PERF_ISO27001_PROCEDURAL_LONG_03', category: 'performance_test', vendor: 'Generic', question: 'What are the specific technical and organizational security controls required under ISO 27001 Annex A for a cloud service provider, focusing on controls related to access management, encryption, network security, and incident response, with implementation guidance for each?', expectedTopics: ['Annex A', 'access management', 'encryption', 'network security', 'cloud controls'], complexity: 'advanced', standard: 'ISO_27001', knowledgeType: 'PROCEDURAL', estimatedTokens: 44 },
    { id: 'PERF_PCIDSS_PROCEDURAL_LONG_04', category: 'performance_test', vendor: 'Generic', question: 'For an e-commerce platform handling payment card data, what are the complete PCI-DSS compliance requirements covering network security, cardholder data protection, vulnerability management, access control, monitoring, and testing, including quarterly and annual obligations?', expectedTopics: ['cardholder data', 'network security', 'vulnerability management', 'monitoring'], complexity: 'advanced', standard: 'PCI_DSS', knowledgeType: 'PROCEDURAL', estimatedTokens: 39 },
    { id: 'PERF_EUAI_SYNTHESIS_LONG_05', category: 'performance_test', vendor: 'Generic', question: 'An organization is developing a generative AI system for customer service that processes personal data. What compliance requirements apply from EU AI Act, GDPR, and ISO 42001, including risk classification, transparency obligations, data protection requirements, and AI governance controls?', expectedTopics: ['EU AI Act', 'GDPR', 'ISO 42001', 'risk classification', 'AI governance'], complexity: 'advanced', standard: 'EU_AI_ACT', knowledgeType: 'SYNTHESIS', estimatedTokens: 46 },
    { id: 'PERF_FEDRAMP_PROCEDURAL_LONG_06', category: 'performance_test', vendor: 'Generic', question: 'What is the complete process for a cloud service provider to achieve FedRAMP authorization at the Moderate impact level, including pre-assessment, system security plan development, control implementation, third-party assessment, authorization decision, and continuous monitoring?', expectedTopics: ['authorization process', 'SSP', '3PAO', 'continuous monitoring'], complexity: 'advanced', standard: 'FedRAMP', knowledgeType: 'PROCEDURAL', estimatedTokens: 42 },
    { id: 'PERF_NISTCSF_PROCEDURAL_LONG_07', category: 'performance_test', vendor: 'Generic', question: 'How should an organization implement the NIST Cybersecurity Framework covering all six functions - Govern, Identify, Protect, Detect, Respond, and Recover - with specific activities, controls, and metrics for each function?', expectedTopics: ['six functions', 'implementation', 'activities', 'metrics'], complexity: 'advanced', standard: 'NIST_CSF', knowledgeType: 'PROCEDURAL', estimatedTokens: 38 },
    { id: 'PERF_HIPAA_RELATIONAL_LONG_08', category: 'performance_test', vendor: 'Generic', question: 'For a healthcare organization implementing both HIPAA and ISO 27001, what are the mappings between HIPAA Security Rule safeguards and ISO 27001 Annex A controls, and how can a single ISMS address both requirements efficiently?', expectedTopics: ['HIPAA', 'ISO 27001', 'mapping', 'ISMS', 'efficiency'], complexity: 'advanced', standard: 'HIPAA', knowledgeType: 'RELATIONAL', estimatedTokens: 41 },
    { id: 'PERF_ISO27701_PROCEDURAL_LONG_09', category: 'performance_test', vendor: 'Generic', question: 'What are the complete requirements for establishing a Privacy Information Management System under ISO 27701, including the additional privacy controls beyond ISO 27001, PII controller and processor obligations, and integration with existing ISMS?', expectedTopics: ['PIMS', 'privacy controls', 'PII controller', 'PII processor'], complexity: 'advanced', standard: 'ISO_27701', knowledgeType: 'PROCEDURAL', estimatedTokens: 39 },
    { id: 'PERF_CMMC_PROCEDURAL_LONG_10', category: 'performance_test', vendor: 'Generic', question: 'For a defense contractor handling Controlled Unclassified Information, what is the path to CMMC Level 2 certification including NIST 800-171 implementation, System Security Plan development, assessment preparation, and third-party certification process?', expectedTopics: ['CMMC Level 2', 'CUI', 'NIST 800-171', 'SSP', 'certification'], complexity: 'advanced', standard: 'CMMC_2_0', knowledgeType: 'PROCEDURAL', estimatedTokens: 39 }
  ],

  RUN_5_VERYLONG: [
    { id: 'PERF_GDPR_SYNTHESIS_VERYLONG_01', category: 'performance_test', vendor: 'ArionComply', question: '[TIER 1: You are ArionComply AI, expert compliance advisor]\n[TIER 2: GDPR Assessment Mode - helping with gap assessment]\n[TIER 3: Industry: Healthcare, Size: SMB (50-250), Region: EU, Frameworks: GDPR+HIPAA, Maturity: Developing]\n[CONTEXT: Organization is healthcare provider with EU and US patients]\n[QUESTION: We need to conduct a comprehensive data protection gap assessment covering both GDPR requirements for EU patient data and HIPAA requirements for US patient health information. What is the systematic workflow to assess our current state, identify gaps, prioritize remediation, and track implementation progress for both regulations simultaneously while avoiding duplicate work where requirements overlap?]', expectedTopics: ['gap assessment', 'GDPR', 'HIPAA', 'workflow', 'dual compliance'], complexity: 'expert', standard: 'GDPR', knowledgeType: 'SYNTHESIS', estimatedTokens: 110 },
    { id: 'PERF_ISO27001_SYNTHESIS_VERYLONG_02', category: 'performance_test', vendor: 'ArionComply', question: '[TIER 1: ArionComply expert advisor]\n[TIER 2: ISO 27001 Implementation Mode]\n[TIER 3: Industry: Financial Services, Size: Enterprise (1000+), Region: Global, Frameworks: ISO27001+SOC2+PCI-DSS, Maturity: Managed]\n[QUESTION: As a global financial services firm, we are implementing ISO 27001 to complement existing SOC 2 and PCI-DSS programs. How do we leverage our existing SOC 2 controls and PCI-DSS security measures to accelerate ISO 27001 implementation, what additional ISO-specific controls are needed, and what is the optimal implementation sequence to achieve certification within 12 months while maintaining existing compliance?]', expectedTopics: ['ISO 27001', 'SOC 2', 'PCI-DSS', 'control leverage', 'implementation sequence'], complexity: 'expert', standard: 'ISO_27001', knowledgeType: 'SYNTHESIS', estimatedTokens: 105 },
    { id: 'PERF_SOC2_SYNTHESIS_VERYLONG_03', category: 'performance_test', vendor: 'ArionComply', question: '[TIER 1: Compliance advisor]\n[TIER 2: Multi-framework mapping mode]\n[TIER 3: Industry: Technology/SaaS, Size: SMB (100-500), Region: US+EU, Frameworks: SOC2+GDPR+ISO27001, Maturity: Developing]\n[QUESTION: We currently have SOC 2 Type II certification. Enterprise customers are now requiring ISO 27001 certification, and we also need GDPR compliance for EU customers. What is the optimal approach to map our existing SOC 2 controls to both ISO 27001 and GDPR requirements, identify the unique controls needed for each framework, and create an implementation roadmap that minimizes duplicate effort while achieving all three certifications?]', expectedTopics: ['SOC 2', 'ISO 27001', 'GDPR', 'control mapping', 'roadmap'], complexity: 'expert', standard: 'SOC_2', knowledgeType: 'SYNTHESIS', estimatedTokens: 108 },
    { id: 'PERF_EUAI_SYNTHESIS_VERYLONG_04', category: 'performance_test', vendor: 'ArionComply', question: '[TIER 1: ArionComply advisor]\n[TIER 2: AI Governance + Risk Assessment]\n[TIER 3: Industry: AI/ML Company, Size: Startup (50), Region: EU+CA, Frameworks: EU_AI_Act+ISO42001+GDPR, Maturity: Initial]\n[QUESTION: We are developing an AI-powered hiring assistant that screens resumes and ranks candidates. Under the EU AI Act, is this high-risk? What specific requirements apply from EU AI Act, how does ISO 42001 AI Management System help us meet those requirements, what GDPR considerations exist for processing candidate personal data, and how does California SB 1047 apply if we operate in California?]', expectedTopics: ['EU AI Act', 'high-risk AI', 'ISO 42001', 'GDPR', 'hiring assistant'], complexity: 'expert', standard: 'EU_AI_ACT', knowledgeType: 'SYNTHESIS', estimatedTokens: 108 },
    { id: 'PERF_GDPR_SYNTHESIS_VERYLONG_05', category: 'performance_test', vendor: 'ArionComply', question: '[TIER 1: Compliance expert]\n[TIER 2: Incident Response + Breach Management]\n[TIER 3: Industry: Retail, Size: Enterprise (5000+), Region: Global, Frameworks: GDPR+CCPA+PCI-DSS+ISO27001+ISO27035, Maturity: Defined]\n[QUESTION: We experienced a data breach affecting customer payment card data and personal information of EU and California residents. What is the complete incident response workflow covering ISO 27035 incident handling, GDPR 72-hour breach notification to DPA, CCPA breach notification to California AG, PCI-DSS incident reporting to card brands and acquiring bank, customer notification requirements under each regulation, and post-incident lessons learned documentation?]', expectedTopics: ['data breach', 'incident response', 'GDPR notification', 'CCPA', 'PCI-DSS'], complexity: 'expert', standard: 'GDPR', knowledgeType: 'SYNTHESIS', estimatedTokens: 108 },
    { id: 'PERF_FEDRAMP_SYNTHESIS_VERYLONG_06', category: 'performance_test', vendor: 'ArionComply', question: '[TIER 1: Expert advisor]\n[TIER 2: Cloud Security Compliance]\n[TIER 3: Industry: Cloud Service Provider, Size: Enterprise, Region: US Federal, Frameworks: FedRAMP+ISO27017+CSA_STAR, Maturity: Managed]\n[QUESTION: As a cloud service provider targeting federal government customers, we need FedRAMP Moderate authorization. How do we leverage our existing ISO 27017 cloud security controls and CSA STAR Level 2 certification to accelerate FedRAMP readiness, what are the FedRAMP-specific NIST 800-53 controls that go beyond ISO and CSA, and what is the end-to-end authorization process including 3PAO selection, SAR development, and authorization timeline?]', expectedTopics: ['FedRAMP', 'ISO 27017', 'CSA STAR', 'NIST 800-53', 'authorization'], complexity: 'expert', standard: 'FedRAMP', knowledgeType: 'SYNTHESIS', estimatedTokens: 105 },
    { id: 'PERF_GDPR_SYNTHESIS_VERYLONG_07', category: 'performance_test', vendor: 'ArionComply', question: '[TIER 1: ArionComply]\n[TIER 2: Privacy Program Development]\n[TIER 3: Industry: Education Technology, Size: SMB, Region: US+EU, Frameworks: GDPR+FERPA+COPPA, Maturity: Initial]\n[QUESTION: We provide educational software to K-12 schools processing student data in US and EU. What privacy program framework addresses GDPR requirements for EU student data, FERPA requirements for US educational records, and COPPA requirements for children under 13, including consent management, data retention policies, security safeguards, and parent rights fulfillment across all three regulations?]', expectedTopics: ['GDPR', 'FERPA', 'COPPA', 'student data', 'privacy program'], complexity: 'expert', standard: 'GDPR', knowledgeType: 'SYNTHESIS', estimatedTokens: 95 },
    { id: 'PERF_HIPAA_SYNTHESIS_VERYLONG_08', category: 'performance_test', vendor: 'ArionComply', question: '[TIER 1: Advisor]\n[TIER 2: Vendor Risk Management]\n[TIER 3: Industry: Healthcare, Size: Large (2000+), Region: US, Frameworks: HIPAA+SOC2+ISO27001, Maturity: Managed]\n[QUESTION: We use multiple cloud vendors (AWS, Azure, GCP) and SaaS providers processing protected health information. What is the comprehensive vendor risk assessment and management program needed to ensure third-party HIPAA Business Associate compliance, evaluate vendor security controls against SOC 2/ISO 27001, manage vendor contracts and BAAs, conduct ongoing vendor monitoring, and maintain vendor risk register?]', expectedTopics: ['vendor risk', 'HIPAA', 'BAA', 'third-party risk', 'vendor management'], complexity: 'expert', standard: 'HIPAA', knowledgeType: 'SYNTHESIS', estimatedTokens: 92 },
    { id: 'PERF_ISO20000_SYNTHESIS_VERYLONG_09', category: 'performance_test', vendor: 'ArionComply', question: '[TIER 1: Expert]\n[TIER 2: IT Service Management + Security Integration]\n[TIER 3: Industry: Managed Service Provider, Size: Medium, Region: Global, Frameworks: ISO20000+ISO27001+SOC2, Maturity: Developing]\n[QUESTION: We provide managed IT services and need both ISO 20000 ITSM and ISO 27001 security certifications plus SOC 2 for customer requirements. How do we integrate incident management, change management, and problem management processes to satisfy ISO 20000 service requirements while also meeting ISO 27001 security incident handling and SOC 2 availability criteria without duplicate processes?]', expectedTopics: ['ISO 20000', 'ISO 27001', 'SOC 2', 'process integration', 'ITSM'], complexity: 'expert', standard: 'ISO_20000', knowledgeType: 'SYNTHESIS', estimatedTokens: 98 },
    { id: 'PERF_SOX_SYNTHESIS_VERYLONG_10', category: 'performance_test', vendor: 'ArionComply', question: '[TIER 1: Advisor]\n[TIER 2: Compliance Program Optimization]\n[TIER 3: Industry: Financial Services, Size: Enterprise, Region: US, Frameworks: SOX+GLBA+PCI-DSS+SOC2, Maturity: Optimizing]\n[QUESTION: Our organization currently maintains separate compliance programs for SOX IT general controls, GLBA Safeguards Rule, PCI-DSS payment security, and SOC 2 service organization controls. How can we consolidate these into an integrated compliance management framework that eliminates duplicate audits and evidence collection, maps controls across all four frameworks, and optimizes resource allocation while maintaining certification for each?]', expectedTopics: ['SOX', 'GLBA', 'PCI-DSS', 'SOC 2', 'integration', 'optimization'], complexity: 'expert', standard: 'SOX', knowledgeType: 'SYNTHESIS', estimatedTokens: 96 }
  ]
};
